version: '3.1'
services:
  stats-service:
    build: statservice
    image: statservice-image
    container_name: statservice_container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/statExploreWithMe
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password12345

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db_container
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=statExploreWithMe
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password12345

  #ewm-service:
   # ports:
    #  - "8080:8080"

  #ewm-db:
   # image: postgres:14-alpine
