version: '3.1'
services:
  ewm-service:
    build: ewmservice
    image: ewmservice-image
    container_name: ewmservice_container
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/mainExploreWithMe
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password12345

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db_container
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=mainExploreWithMe
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password12345

  stats-service:
    build: statservice
    image: statservice-image
    container_name: statservice_container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/statExploreWithMe
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password12345

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db_container
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=statExploreWithMe
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password12345



