CREATE TABLE IF NOT EXISTS endpoint_hit
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app               VARCHAR(320) NOT NULL,
    uri               VARCHAR(320) NOT NULL,
    ip                VARCHAR(320) NOT NULL,
    time_stamp        TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT   pk_endpoint_hit            PRIMARY KEY (id),
    CONSTRAINT   app_is_blank               CHECK (app NOT LIKE ' ' AND app NOT LIKE ''),
    CONSTRAINT   uri_is_blank               CHECK (uri NOT LIKE ' ' AND uri NOT LIKE ''),
    CONSTRAINT   ip_is_blank                CHECK (ip NOT LIKE ' ' AND ip NOT LIKE '')
);

